### ISSUE TITLE
İndex.html

### ISSUE THREAD

**Issue by Kamrannv** [turanbalayev/philosophy-html-layout#1]
Pagination-i bir section olaraq ayırmaq əvəzinə aid olduğu sectionda tutmaq olardı. Footer hissəni isə lap yuxarıdan(popular posts) hissədən başlamaq biraz düzgün yanaşma kimi görünmür. O hissə özü ayrı bir section-dir, sağ hissəsində olan about philosophy hissəni də semantikaya xas olaraq aside içində yazmaq olardı . Footer hissəni də taglar olan hissədən sonraya aid etmək lazımdır.

**Comment by turanbalayev** [comment]
1. Pagination hissəsini həll elədim.
2. Footera yazdığım hissə bütün templeytdə eyni qaldığı üçün elə yazmışam. Semantic olaraq məncə də Popular Posts ayrı sectiondır, sadəcə templeytin bütün səhifələrində o hissə eyni qalır ona görə footerin içində yazmışdım.

**Comment by Kamrannv** [comment]
Aydındır. Eyni qalsa belə ayrıca layouta çıxardıb footerdən qabaqkı section olaraq göstərmək olar(backend yazılanda).
